// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sylchabdkxrkkjxqnnbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5bGNoYWJka3hya2tqeHFubmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTI0MTMsImV4cCI6MjA2MDI2ODQxM30.hICYUSTmmTY3dIF3Wy6htUaTzVxxFkZkDNtyR_in0J0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);